leftnav:
- identifier: e7813f17-e637-7155-8463-719b757bf82b
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: ac2bd584-dff3-f2da-cc5e-116d36c23cd6
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: c76d4030-fd4d-4539-dfe0-927bb9fd85a2
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 4944bd9d-c145-19b4-4f0a-988b23c4ad3b
  name: Recitations
  url: /pages/recitations
  weight: 40
- identifier: f72b4413-96ab-aaff-a22c-899e90f78419
  name: Study Materials
  url: /pages/study-materials
  weight: 50
- identifier: 2b5408ac-832e-fdfa-516b-43aa9dad8336
  name: Exams
  url: /pages/exams
  weight: 60
